apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-nginx-image
 # namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
