replicaCount: 1

app:
  name: new

image:
  repository: sonalilamkhade/custom-nginx
  tag: "6"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: nginx.jenkins.local
  className: nginx  
